### ISSUE TITLE
[META] Improve code quality

### ISSUE THREAD

**Issue by prusnak** [lnbits/lnbits#1307]
At Trezor, we've been using several tools to improve our Python code quality. This is a meta issue to collect ideas and track their progress.

The great thing about lnbits is that this repo already uses the following:

- [x] black
- [x] isort
- [x] mypy
- [x] prettier

However, there are also these 3 tools that have helped us tremendously:

- [x] flake8 - https://flake8.pycqa.org/ => https://github.com/lnbits/lnbits/pull/1369
- [x] pyright - https://github.com/microsoft/pyright => https://github.com/lnbits/lnbits/pull/1444
- [x] pylint - https://pylint.pycqa.org/ => https://github.com/lnbits/lnbits/pull/1369

In fact, pyright is so awesome, we dropped mypy completely (🤯), but I guess it does not hurt to keep both mypy and pyright. 

But first things first ... I'd like to first address the flake8 issues. Then proceed with pylint and pyright issues.

I'll record PR related to this meta issue in the comments below.

**Comment by dni** [comment]
pyright PR: https://github.com/lnbits/lnbits/pull/1356
initial draft, i recklessless gone throw core, and broke a lot of things, will fix asap

**Comment by prusnak** [comment]
Pyright being added as Node dev dependency in https://github.com/lnbits/lnbits/pull/1367

**Comment by dni** [comment]
why as nodejs? i tried to get rid of prettier before so we dont have any npm stuff ;)

**Comment by prusnak** [comment]
> why as nodejs? i tried to get rid of prettier before so we dont have any npm stuff ;)

Because pyright is written in Typescript and it's native environment is NodeJS. Using pyright via pypi is just adding an extra unofficial layer of code (and problems).

**Comment by prusnak** [comment]
Flake8 being added as dev dependency in https://github.com/lnbits/lnbits/pull/1369
