### ISSUE TITLE
Installable Releases

### ISSUE THREAD

**Issue by motorina0** [lnbits/lnbits#1385]
- [x] stars at repo level
- [x] editors choice for extensions (recommended for you)
- [x] install similar with mange

###  Todo
- [ ] show notifications for extensions
  - info: extension deprecated
  - critical: extension has vulnerability
- [ ] github release: show dependencies
- [ ] show latest tag
- [ ] fix latest when more repos are present
- [ ] match github repo stars with repo
- [ ] downgrade extension -> db cannot rollback
- [ ] show extension review (allow voting)

### how
- re-installed previous extensions if:
  - there is a `dbversions`
  - there is a `repos`
